version: 0.1.{build}
skip_non_tags: true
cache:
  - openssl-1.0.2j-fips-x86_64.zip
  - pyside-setup-everywhere-src-5.13.1.zip
environment:
  matrix:
  - PYTHON: C:\Python35
    TAG: cp35
    VERSION: 5.13.0
    PLATFORM: x86
    DISTUTILS_USE_SDK: 1
    APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2017
    QTDIR: "C:\\Qt\\%VERSION%\\msvc2017"
    PATH: "%QTDIR%\\bin;%PYTHON%;%PYTHON%\\Scripts;%PATH%"
    CONFIG: Release
init:
  - ps: iex ((new-object net.webclient).DownloadString('https://raw.githubusercontent.com/appveyor/ci/master/scripts/enable-rdp.ps1'))
build:
  parallel: true
  verbosity: minimal
build_script:
- ps: >-
    Function Unzip()

    {
        param([string]$ZipFile,[string]$TargetFolder)
        #确保目标文件夹必须存在
        if(!(Test-Path $TargetFolder))
        {
            mkdir $TargetFolder
        }
        $shellApp = New-Object -ComObject Shell.Application
        $files = $shellApp.NameSpace($ZipFile).Items()
        $shellApp.NameSpace($TargetFolder).CopyHere($files)
    }


    mkdir files


    if(-not (Test-Path openssl-1.0.2j-fips-x86_64.zip )) {
        Start-FileDownload 'https://sourceforge.net/projects/openssl/files/openssl-1.0.2j-fips-x86_64/openssl-1.0.2j-fips-x86_64.zip'
        Unzip -ZipFile openssl-1.0.2j-fips-x86_64.zip -TargetFolder files\openssl
    }


    if(-not (Test-Path openssl-1.0.2j-fips-x86_64.zip )) {
        Start-FileDownload 'https://download.qt.io/official_releases/QtForPython/pyside2/PySide2-5.13.1-src/pyside-setup-everywhere-src-5.13.1.zip'
        Unzip -ZipFile pyside-setup-everywhere-src-5.13.1.zip -TargetFolder files\pyside2
    }


    dir files


    dir files\openssl


    dir files\pyside2
- cmd: >-
    "C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\vcvarsall.bat" %PLATFORM%

    python  --version

    xcopy "Windows\%PLATFORM%\PyQt5\Qt\*" %QTDIR% /S /E /Y /D

    set PATH=%PATH%;%cd%\files\openssl\bin;

    cd files\pyside2

    python setup.py build --qmake=%QTDIR%\bin\qmake.exe --openssl=%cd%\files\openssl\bin