version: 0.1.{build}
skip_non_tags: true
environment:
  matrix:
  - PYTHON: C:\Python35
    TAG: cp35
    VERSION: 5.13.0
    PLATFORM: x86
    DISTUTILS_USE_SDK: 1
    APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2017
    QTDIR: "C:\\Qt\\%VERSION%\\msvc2017"
    PATH: "%QTDIR%\\bin;%PYTHON%;%PYTHON%\\Scripts;%PATH%"
    CONFIG: Release
init:
  - ps: iex ((new-object net.webclient).DownloadString('https://raw.githubusercontent.com/appveyor/ci/master/scripts/enable-rdp.ps1'))
build:
  parallel: true
  verbosity: minimal
build_script:
- cmd: >-
    "C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\vcvarsall.bat" %PLATFORM%

    C:\Python35\python  --version

    xcopy "Windows\%PLATFORM%\PyQt5\Qt\*" %QTDIR% /S /E /Y /D

    C:\Python35\python build.py -p Windows -a x86  --qmake=%QTDIR%\bin\qmake.exe